Added: a field 'sendPath' for specifying the local directory structure
hotwax/mantle-shopify-connector pull request #23
Opened 2023-09-20 11:08 UTC by Nidhipal09

Currently, we are using 'receivePath' to specify the local directory structure of where the fetched file should be kept. This restricts our control to specify a separate file path which could be outside of Moqui also. 
So, we have added a field 'sendPath' in the 'SystemMessageType' data for 'OMSFulfillmentFeed' to specify the local directory structure.

2023-09-21 11:31 UTC, mridulpathak commented on data/ShopifyConfigDemoData.xml
> +                                             receiveResponseEnumId="MsgRrMove" receiveMovePath=""
Need to add it in ShopifySetupSeedData.xml too.

2023-09-22 07:27 UTC, Nidhipal09 commented on data/ShopifyConfigDemoData.xml
> +                                             receiveResponseEnumId="MsgRrMove" receiveMovePath=""
Done Sir.

2023-09-27 11:02 UTC, gurveenbagga commented on data/ShopifyConfigDemoData.xml
> +                                             sendPath=""/>
we can add the sendPath and receivePath field values in the demo data.

2023-09-27 11:05 UTC, gurveenbagga commented on data/ShopifySetupSeedData.xml
> +                                             sendPath=""/>
Following the pattern to have this as a seed data, and specific details are added as part of separate data reader like ext or demo, then we could skip any update on this data.

2023-09-27 11:07 UTC, gurveenbagga commented on data/ShopifyConfigDemoData.xml
> +                                             sendPath=""/>
@Nidhipal09 whenever we add new data, we should add in ext-upgrade data file also to avoid missing this "data change" when new releases are created.

2023-10-10 05:14 UTC, Nidhipal09 commented on data/ShopifyConfigDemoData.xml
> +                                             sendPath=""/>
Done ma'am.

2023-10-10 05:15 UTC, Nidhipal09 commented on data/ShopifyConfigDemoData.xml
> +                                             sendPath=""/>
Done ma'am.

2023-10-26 10:02 UTC, janvi04 approved these changes

2023-10-26 10:09 UTC, janvi04 requested changes

2023-10-26 10:09 UTC, janvi04 commented on data/UpgradeData_Upcoming.xml
> +    <moqui.service.message.SystemMessageType systemMessageTypeId="OMSFulfillmentFeed"
In the upgrade data we can just add the system message type id and the sendPath.
We should only add what has changed along with the systemmessageTypeId.

2023-10-26 10:11 UTC, janvi04 approved these changes

2023-10-31 10:28 UTC, gurveenbagga approved these changes

2023-10-31 10:55 UTC, merged